#----------------------- wcopy' MAKEFILE --------------------- 


# --- 1.- Options for base system ---


#--------------------
# Consts for SUNOS   
#--------------------
 
CC        = gcc
LIBPATH   = -L/usr/lib
HPATH     = -I.. -I../lib/
SRCDIR    = ..
CFLAGS    = -g -Wall -D__SUNOS__ 
LIBLINK   = ../lib/wpplib/wpplib.a ../lib/weblib/weblib.a ../lib/corelib/corelib.a  -lnsl -lsocket 


#--------------------
# Consts for LINUX
#--------------------
 
#CC        = gcc
#LIBPATH   = -L/usr/lib
#HPATH     = -I../  -I../../corelib  -I../../weblib
#SRCDIR    = ..
#CFLAGS    = -g   -Wall -D__LINUX__ 
#LIBLINK   = ../../weblib/weblib.a ../../corelib/corelib.a



# --- 2.- library profile distribution -------

PROGNAME  = ./wcopy
OBJECT    = \
	    $(SRCDIR)/wcopy/l_wcpdl.o        \
            $(SRCDIR)/wcopy/l_wcpmsg.o       \
            $(SRCDIR)/wcopy/l_wcopy.o        \
            $(SRCDIR)/wcopy/wcopy.o 

 

#--------------------------
# Reglas de compilacion ...
#-------------------------- 

all:      init  wcopy
refast:   clean wcopy
fast:     wcopy

wcopy:   $(OBJECT)
	@echo "   Linking :"
	@echo "     "$(PROGNAME)
	@$(CC)  $(CFLAGS) -o $(PROGNAME)   $(OBJECT) $(LIBLINK)
	@sync

init:
	@echo [2J 
	@echo "[1;1f" 
	@echo "" 
	@echo "    wcopy"
	@echo "   -------" 
	@echo "" 
	@echo "   Computer  :"
	@echo "     "`uname -a` 
	@echo "   Options   :"
	@echo "     "$(CFLAGS)
	@echo "   Directory :"
	@echo "     "$(HPATH)
	@echo "   Compiling :"

%.o: %.c
	@echo "     $< ..." 
	@$(CC)  $(CFLAGS) $(HPATH) -c $< -o $@ 


clean: 
	@echo "   Removing trash..."
	@rm -fr $(OBJECT) 
	@rm -fr $(PROGNAME)
	@echo "   Trash succesfully removed !."



# ----------------------------------------------------------------

